name: CI & CD for Sea_Conquest game

on:
  push:
    branches: [ master ]
    paths-ignore:
     -'Docs/**
      
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: "[16.4,16.6]"

    - name: MSBuild
      working-directory: Project II Game
      run: MSBuild Sea_Conquest.sln /property:Configuration=Release
    
    - name: Release
      uses: "marvinpinto/action-automatic-releases@v1"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        automatic_release_tag: lastest
        title: Sea_Conquest_Release
        files: | 
          README.md
          LICENSE.md
            '**/Game/**'
            !*.obj
            !*.ibd
            !*.pdb
          
          
